### ISSUE TITLE
images aren't responsive

### ISSUE THREAD

**Issue by hdp1** [dudaster/eletheme#13]
When using the templates and you add an image in the Wordpress editor, it isn't responsive. The featured image works okay.

So you create your templates, then create for example a custom post, add your content using the Wordpress editor, all of the text resizes correctly, but the images don't resize.

**Comment by dudaster** [comment]
It will be fixed in the next update

**Comment by dudaster** [comment]
I've made some test and the images resize when you shrink the content.
Please let me know what you mean by Images don't resize. Send me a link where I can see what's happening.

**Comment by hdp1** [comment]
I have this running locally at the moment. I have done some more tests and the problem only occurs when you add a caption to the image?

**Comment by hdp1** [comment]
![test-caption](https://user-images.githubusercontent.com/36894788/36748884-1b66baea-1bf1-11e8-917f-08fdac2b5900.jpg)

**Comment by hdp1** [comment]
I have added some css to fix this.

I would like to say that this theme is awesome and thank you for making it available.

**Comment by dudaster** [comment]
I wasn't able to reproduce this bug. It could be some css from another plugin. (check for .wp-caption-text)

I would love to help you if you put it online I'll point you to the problem ASAP.

**Comment by hdp1** [comment]
I have added some css for .wp-caption which has made the images resize. The issue only occurs when you use the templates and the Wordpress editor. If you create a page or a post and do everything in Elementor, it works fine. I also needed to add css for paragraphs and bullet lists when using the templates.
Thank you for your help.

**Comment by dudaster** [comment]
So when you remove the css rules you made for .wp-caption is it working?
I recommend to create a child theme of eletheme (there are plenty of plugins that can generate one with a push of a button) and add all the stuff in the style.css of the child theme.

**Comment by hdp1** [comment]
When I remove the my css rules it doesn't work.
I am using a custom css plugin to add the css.
I tried the css styles that Wordpress state on their website, which did work, but not correctly.
But using the following solved the issue completely.

.wp-caption {
    /* Force the box to be 100% */
    width: 100% !important;
    text-align: center;
  }

Thank you for your help and advice.

**Comment by dudaster** [comment]
Glad the issue is solved!
