### ISSUE TITLE
Not all Wordpress widgets load

### ISSUE THREAD

**Issue by hdp1** [dudaster/eletheme#16]
Some of the normal Wordpress widgets don't load when you try to add them to the eletheme templates. The Wordpress text widget for example just says "loading" but never loads as per the attached image. 
![wordpress widget](https://user-images.githubusercontent.com/36894788/37334295-6abbbe9e-26a3-11e8-8b75-9f13fedb8dec.jpg)

Archives and meta load but the elementor widget box just says loading.

All of the Elementor widgets work okay.

**Comment by dudaster** [comment]
I think is an elementor issue which version are you using?

**Comment by dudaster** [comment]
I've updated Elementor to Elementor 2.0.0 - Beta1 and managed to reproduce the issue. And the issue was with any other theme. It seems to be fixed with Elementor 2.0.0 - Beta2. Please confirm if this was the issue so I can close this!

**Comment by hdp1** [comment]
Hi, Sorry, I have been rolling backwards and forwards with different versions. I didn't install Beta1, but have just tried Beta2 and it works okay with this version.
