### ISSUE TITLE
Downloaded eletheme.zip.  McAffee reports potential virus!

### ISSUE THREAD

**Issue by lwoods** [dudaster/eletheme#19]
I download zip files all of the time without getting this message!

**Comment by dudaster** [comment]
You can try this link to download https://github.com/dudaster/eletheme/releases/latest
Let me know if you get the same result.

**Comment by lwoods** [comment]
That one did not get the message.  Thanks.

On Mon, Jun 18, 2018 at 6:26 AM, Liviu Duda <notifications@github.com>
wrote:

> You can try this link to download https://github.com/dudaster/
> eletheme/releases/latest
> <https://mailtrack.io/trace/link/674349cb850bb943e9f7bee3331cd8891164825a?url=https%3A%2F%2Fgithub.com%2Fdudaster%2Feletheme%2Freleases%2Flatest&userId=1611542&signature=53df58b10b19c8e9>
> Let me know if you get the same result.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://mailtrack.io/trace/link/63d5c4bc0269738ef357794ccdd24ca308930273?url=https%3A%2F%2Fgithub.com%2Fdudaster%2Feletheme%2Fissues%2F19%23issuecomment-398053236&userId=1611542&signature=60bd2c07a309900a>,
> or mute the thread
> <https://mailtrack.io/trace/link/ac562369ad782112b38d2f9f53721248ecc0937b?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAALE2X4okafNQsvF7YDNu8mLpsMEHQouks5t96qWgaJpZM4Urvb1&userId=1611542&signature=66220695f73f83ac>
> .
>



-- 

Office:  623-556-8949
Cell:     602-369-5049


--- NOTICE ---


This message is for the designated recipient only and may contain
confidential, privileged or proprietary information.  If you have received
it in error, please notify the sender immediately and delete the original
and any copy or printout.  Unintended recipients are prohibited from making
any other use of this e-mail.  Although we have taken reasonable
precautions to ensure no viruses are present in this e-mail, we accept no
liability for any loss or damage arising from the use of this e-mail or
attachments, or for any delay or errors or omissions in the contents which
result from e-mail transmission.
