### ISSUE TITLE
ElE CUSTOM SKIN: Problem Publishing or Updating

### ISSUE THREAD

**Issue by Makramgit** [dudaster/eletheme#21]
Hi,

With the latest elemntor and elementor pro installed, when trying to edit an elementor template of type "loop" i am unable to publish or update inside elementor.  Nothing happens when pressing the publish button.

Thx for your help and this great plugin

**Comment by Makramgit** [comment]
This is the error i see in the console:

Uncaught TypeError: Cannot read property 'label' of undefined
    at editor.min.js?ver=2.1.0:2
    at Function.m.each.m.forEach (load-scripts.php?c=1&load[]=underscore,jquery-core,jquery-migrate,backbone,shortcode,utils,wp-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload,jqu&load[]=ery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable&ver=4.9.8:5)
    at m.(/ha/wp-admin/anonymous function) [as each] (http://localhost/ha/wp-admin/load-scripts.php?c=1&load%5B%5D=underscore,jquery-core,jquery-migrate,backbone,shortcode,utils,wp-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload,jqu&load%5B%5D=ery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable&ver=4.9.8:5:15545)
    at n.updateConditionsOptions (editor.min.js?ver=2.1.0:2)
    at n.initialize (editor.min.js?ver=2.1.0:2)
    at n.e.View (load-scripts.php?c=1&load[]=underscore,jquery-core,jquery-migrate,backbone,shortcode,utils,wp-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload,jqu&load[]=ery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable&ver=4.9.8:16)
    at n.constructor (backbone.marionette.min.js?ver=2.4.5:22)
    at n.constructor (backbone.marionette.min.js?ver=2.4.5:22)
    at n.constructor (backbone.marionette.min.js?ver=2.4.5:23)
    at n [as constructor] (load-scripts.php?c=1&load[]=underscore,jquery-core,jquery-migrate,backbone,shortcode,utils,wp-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload,jqu&load[]=ery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable&ver=4.9.8:16)
(anonymous) @ editor.min.js?ver=2.1.0:2
m.each.m.forEach @ load-scripts.php?c=1&load[]=underscore,jquery-core,jquery-migrate,backbone,shortcode,utils,wp-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload,jqu&load[]=ery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable&ver=4.9.8:5
m.(anonymous function) @ load-scripts.php?c=1&load[]=underscore,jquery-core,jquery-migrate,backbone,shortcode,utils,wp-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload,jqu&load[]=ery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable&ver=4.9.8:5
updateConditionsOptions @ editor.min.js?ver=2.1.0:2
initialize @ editor.min.js?ver=2.1.0:2
e.View @ load-scripts.php?c=1&load[]=underscore,jquery-core,jquery-migrate,backbone,shortcode,utils,wp-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload,jqu&load[]=ery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable&ver=4.9.8:16
constructor @ backbone.marionette.min.js?ver=2.4.5:22
constructor @ backbone.marionette.min.js?ver=2.4.5:22
constructor @ backbone.marionette.min.js?ver=2.4.5:23
n @ load-scripts.php?c=1&load[]=underscore,jquery-core,jquery-migrate,backbone,shortcode,utils,wp-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload,jqu&load[]=ery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable&ver=4.9.8:16
n @ load-scripts.php?c=1&load[]=underscore,jquery-core,jquery-migrate,backbone,shortcode,utils,wp-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload,jqu&load[]=ery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable&ver=4.9.8:16
n @ load-scripts.php?c=1&load[]=underscore,jquery-core,jquery-migrate,backbone,shortcode,utils,wp-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload,jqu&load[]=ery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable&ver=4.9.8:16
n @ load-scripts.php?c=1&load[]=underscore,jquery-core,jquery-migrate,backbone,shortcode,utils,wp-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload,jqu&load[]=ery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable&ver=4.9.8:16
buildChildView @ backbone.marionette.min.js?ver=2.4.5:22
addChild @ backbone.marionette.min.js?ver=2.4.5:22
(anonymous) @ backbone.marionette.min.js?ver=2.4.5:22
(anonymous) @ load-scripts.php?c=1&load[]=underscore,jquery-core,jquery-migrate,backbone,shortcode,utils,wp-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload,jqu&load[]=ery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable&ver=4.9.8:5
m.each.m.forEach @ load-scripts.php?c=1&load[]=underscore,jquery-core,jquery-migrate,backbone,shortcode,utils,wp-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload,jqu&load[]=ery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable&ver=4.9.8:5
showCollection @ backbone.marionette.min.js?ver=2.4.5:22
_renderChildren @ backbone.marionette.min.js?ver=2.4.5:22
_renderChildren @ backbone.marionette.min.js?ver=2.4.5:23
render @ backbone.marionette.min.js?ver=2.4.5:23
_renderView @ backbone.marionette.min.js?ver=2.4.5:22
show @ backbone.marionette.min.js?ver=2.4.5:22
showConditionsModal @ editor.min.js?ver=2.1.0:2
onClickButtonPublish @ editor.min.js?ver=2.1.0:2
dispatch @ load-scripts.php?c=1&load[]=underscore,jquery-core,jquery-migrate,backbone,shortcode,utils,wp-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload,jqu&load[]=ery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable&ver=4.9.8:9
r.handle @ load-scripts.php?c=1&load[]=underscore,jquery-core,jquery-migrate,backbone,shortcode,utils,wp-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload,jqu&load[]=ery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable&ver=4.9.8:9

**Comment by dudaster** [comment]
@Makramgit hang tight! Update coming tomorrow.

**Comment by dudaster** [comment]
if you wanna fix it now:
go to wp-content/plugins/ele-custom-skin/theme-builder/init.php
at line 42 (or whatever) you'll find this:

`$settings = array_merge_recursive($settings, $add_settings);`

replace with this :

`if (!array_key_exists('loop', $settings['theme_builder']['types'])) $settings = array_merge_recursive($settings, $add_settings);`

**Comment by Makramgit** [comment]
Thx a lot @dudaster. It worked!

**Comment by dudaster** [comment]
Update is up.
