### ISSUE TITLE
Grid layout issue with Post widget in Elementor 2.1.1

### ISSUE THREAD

**Issue by collindavis** [dudaster/eletheme#22]
I exported Elementor templates to new install/instance of Wordpress. When editing the template for the custom skin, everything looks fine. When I add the Posts widget to a page and assign the custom skin, it also looks fine. But when I view the page on the front end (as a user) the layout is not right. 

Screenshot in Elementor editor: https://www.dropbox.com/s/jnvwcjmmijkgufj/ele-elementor-editor.png?dl=0
Screenshot on frontend: https://www.dropbox.com/s/7vt501t3jojuzj9/ele-page-frontend.PNG?dl=0

Any thoughts how to fix?

**Comment by dudaster** [comment]
Can you delete the widget and add it again?

**Comment by collindavis** [comment]
Tried that but no luck. Even tried building a new template from scratch. The issue does not occur when a classic or card skin is used. 

Also tried deactivating and deleting the plugin and then reinstalling but it still did not work.

**Comment by dudaster** [comment]
Give me access and I’ll investigate myself!

**Comment by collindavis** [comment]
I've narrowed the issue down to a Text Editor widget which contains a
shortcode for a Pod that contains HTML code. Why it won't work, I have no
idea, but I'm trying to figure out a workaround.

**Comment by dudaster** [comment]
Keep me posted!

**Comment by collindavis** [comment]
I created a custom shortcode to insert my HTML into a Pod field, and then added the Pod field into my LOOP template. 

For whatever reason the Pod field broke the LOOP template when I used HTML, but the shortcode does not.

**Comment by dudaster** [comment]
Could it be because the html was truncated somehow?

**Comment by collindavis** [comment]
When I viewed the source code of the page it had not truncated the HTML
code. It showed fine, but just caused a conflict with the way the layout
was rendered.
