### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by ScalableB2B** [dudaster/eletheme#24]
I created a loop template, conditioned it to show in "archive" but when I try to choose "custom" I get this error 
![image](https://user-images.githubusercontent.com/42558502/44372597-af7ae180-a4b2-11e8-9d8c-652c73b2661a.png)

What am I missing?

**Comment by dudaster** [comment]
It is not an error message, it is an instruction.

**Comment by ScalableB2B** [comment]
Can Featured Image be used as background image?

**Comment by dudaster** [comment]
It should.

**Comment by dudaster** [comment]
I tested it and it is not working anymore it seems. It was working on ep 2.0 but not with 2.1. I bet with ep 2.2 would have this custom skin embeded.

**Comment by alirexa** [comment]
> I tested it and it is not working anymore it seems. It was working on ep 2.0 but not with 2.1. I bet with ep 2.2 would have this custom skin embeded.

the feature image as background still not working?

**Comment by dudaster** [comment]
Still in the works
