### ISSUE TITLE
Search Page is entirely empty, any idea on where to troubleshoot?

### ISSUE THREAD

**Issue by NJseo** [dudaster/eletheme#25]
I cannot figure this one out. I set debug to true but that is no help. 
There is no template for search appearing.

https://logotized.com/?s=&location_data=08527&distance=100&projectType=19

**Comment by NJseo** [comment]
So, I had to delete and reupload the theme, but it seems as though I cannot push custom queries to it

$args = array(//'relation' => 'AND',
            'posts_per_page'    => 10,
            'status'            => 'publish',
            'post_type'		    => 'post',
            //'cat'		        => $_GET['projectType'],
            'meta_query'	    => array(
                    'meta_key'		    => 'zip_code',
                    'meta_value'		=> array('18527'),
                    'compare'	        => 'IN',
            ),
            'orderby' => array(
			        //'meta_value' => 'ASC',
			        'zip_code' => 'DESC',
			),
        );
//
        // update meta query
	    $query->set('query', $args);

**Comment by dudaster** [comment]
do you have this themplates?

 _[default]_[search]
container for search results
_[default]_[no-results]
template for no results

**Comment by juniordagostim** [comment]
Hello! Sorry for open it again, but I'm having problems with the search results too.
I have downloaded all the theme and uploaded as it is; already have the templates but I'm not a expert user, I confess, and I don't know what's happening. A blank page is everything that I got.
Could you helpe me please?
