### ISSUE TITLE
502 bad gateway when loading elementor edit page

### ISSUE THREAD

**Issue by LinearDynamics** [dudaster/eletheme#28]
![image](https://user-images.githubusercontent.com/32169863/47579160-37e58a80-d919-11e8-9d90-64dc3515f504.png)

If I disable the Ele Custom Skin plugin, the issue goes away.

**Comment by dudaster** [comment]
It could be many things (probably a memory issue).
This happend after you installed and design a loop template?
This happend when you just installed ele custom skin without doin anything but activate it?

Please alse read why 502 Erorr my occure: https://www.lifewire.com/502-bad-gateway-error-explained-2622939
