### ISSUE TITLE
the_content funtion in the current template

### ISSUE THREAD

**Issue by madbradjohnson** [dudaster/eletheme#29]
HI

I have just installed your plugin and tested it on my site. 

THe problem is i cannot edit any existing sections, headers, footers, anything really. The only thing I can edit is an archive template. 

I cannot create anything new except archive template.

The error is: Sorry, the content area was not found in your page.

**Comment by dudaster** [comment]
Which plug-in exactly? And what theme do you use?

**Comment by madbradjohnson** [comment]
Wow! That was in incredibly quick response. It is the custom skins plugin and I just resolved the issue by deactivating Elementor Addons. Trust me. You are getting 5 stars for this! INCREDIBLE! By the way. This was referred to me by David Decker of Toolbar Elementor Addons.

**Comment by dudaster** [comment]
Thanks!
