### ISSUE TITLE
Show posts (events) based on todays date or greater?

### ISSUE THREAD

**Issue by sigersmit** [dudaster/eletheme#34]
Hi,
Love this plugin, makes elementor almost complete.. Is it possible to filter posts with a custom date field (e.g. start date event) only with date today and greater then today? And if yes, how to do that?
Thank you!

**Comment by dudaster** [comment]
Unfortunatly ECS is only a **skin** for Elementor **Pro Posts Widget** wich handles the queries.

**Comment by sigersmit** [comment]
OK, Thanks for your quick reply!
